# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FKNV/test/test.srcs/sources_1/ip/c_addsub_d0Bx/c_addsub_d0Bx.xci
# IP: The module: 'c_addsub_d0Bx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/test/test.gen/sources_1/ip/c_addsub_d0Bx/c_addsub_d0Bx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_d0Bx'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/FKNV/test/test.srcs/sources_1/ip/c_addsub_d0Bx/c_addsub_d0Bx.xci
# IP: The module: 'c_addsub_d0Bx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/test/test.gen/sources_1/ip/c_addsub_d0Bx/c_addsub_d0Bx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_d0Bx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
