# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FKNV/get_pixel_test/get_pixel_test.srcs/sources_1/ip/mult_gen_signed/mult_gen_signed.xci
# IP: The module: 'mult_gen_signed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/get_pixel_test/get_pixel_test.gen/sources_1/ip/mult_gen_signed/mult_gen_signed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_signed'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/FKNV/get_pixel_test/get_pixel_test.srcs/sources_1/ip/mult_gen_signed/mult_gen_signed.xci
# IP: The module: 'mult_gen_signed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/get_pixel_test/get_pixel_test.gen/sources_1/ip/mult_gen_signed/mult_gen_signed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_signed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
