# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FKNV/get_pixel_test/get_pixel_test.srcs/sources_1/ip/c_addsub_d1Bx/c_addsub_d1Bx.xci
# IP: The module: 'c_addsub_d1Bx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/get_pixel_test/get_pixel_test.gen/sources_1/ip/c_addsub_d1Bx/c_addsub_d1Bx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_d1Bx'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/FKNV/get_pixel_test/get_pixel_test.srcs/sources_1/ip/c_addsub_d1Bx/c_addsub_d1Bx.xci
# IP: The module: 'c_addsub_d1Bx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/get_pixel_test/get_pixel_test.gen/sources_1/ip/c_addsub_d1Bx/c_addsub_d1Bx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_addsub_d1Bx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
