# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.srcs/sources_1/bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0.xci
# IP: The module: 'SD2HDMI_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD2HDMI_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD2HDMI_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.srcs/sources_1/bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0.xci
# IP: The module: 'SD2HDMI_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD2HDMI_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD2HDMI_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
