# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SD2HDMI.xdc

# Block Designs: bd/SD2HDMI/SD2HDMI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI || ORIG_REF_NAME==SD2HDMI} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_processing_system7_0_1/SD2HDMI_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_processing_system7_0_1 || ORIG_REF_NAME==SD2HDMI_processing_system7_0_1} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_axi_vdma_0_0/SD2HDMI_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_axi_vdma_0_0 || ORIG_REF_NAME==SD2HDMI_axi_vdma_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_xbar_0/SD2HDMI_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_xbar_0 || ORIG_REF_NAME==SD2HDMI_xbar_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_ps7_0_axi_periph_0/SD2HDMI_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_ps7_0_axi_periph_0 || ORIG_REF_NAME==SD2HDMI_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_rst_ps7_0_100M_0/SD2HDMI_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_rst_ps7_0_100M_0 || ORIG_REF_NAME==SD2HDMI_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_v_axi4s_vid_out_0_0/SD2HDMI_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==SD2HDMI_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_v_tc_0_0/SD2HDMI_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_v_tc_0_0 || ORIG_REF_NAME==SD2HDMI_v_tc_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_axi_dynclk_0_0/SD2HDMI_axi_dynclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_axi_dynclk_0_0 || ORIG_REF_NAME==SD2HDMI_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_rgb2dvi_0_0/SD2HDMI_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_rgb2dvi_0_0 || ORIG_REF_NAME==SD2HDMI_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_smartconnect_0_0/SD2HDMI_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_smartconnect_0_0 || ORIG_REF_NAME==SD2HDMI_smartconnect_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_proc_sys_reset_0_0/SD2HDMI_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_proc_sys_reset_0_0 || ORIG_REF_NAME==SD2HDMI_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/SD2HDMI/ip/SD2HDMI_auto_pc_0/SD2HDMI_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SD2HDMI_auto_pc_0 || ORIG_REF_NAME==SD2HDMI_auto_pc_0} -quiet] -quiet

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/SD2HDMI_ooc.xdc
