# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.srcs/sources_1/bd/SD2HDMI/ip/SD2HDMI_processing_system7_0_1/SD2HDMI_processing_system7_0_1.xci
# IP: The module: 'SD2HDMI_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/ip/SD2HDMI_processing_system7_0_1/SD2HDMI_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD2HDMI_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.srcs/sources_1/bd/SD2HDMI/ip/SD2HDMI_processing_system7_0_1/SD2HDMI_processing_system7_0_1.xci
# IP: The module: 'SD2HDMI_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/SD2HDMI/SD2HDMI/SD2HDMI.gen/sources_1/bd/SD2HDMI/ip/SD2HDMI_processing_system7_0_1/SD2HDMI_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'SD2HDMI_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
