# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FKNV/bicubic_pixel_caculate/bicubic_pixel_caculate.srcs/sources_1/ip/mult_gen_singed/mult_gen_singed.xci
# IP: The module: 'mult_gen_singed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/bicubic_pixel_caculate/bicubic_pixel_caculate.gen/sources_1/ip/mult_gen_singed/mult_gen_singed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_singed'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: F:/FKNV/bicubic_pixel_caculate/bicubic_pixel_caculate.srcs/sources_1/ip/mult_gen_singed/mult_gen_singed.xci
# IP: The module: 'mult_gen_singed' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FKNV/bicubic_pixel_caculate/bicubic_pixel_caculate.gen/sources_1/ip/mult_gen_singed/mult_gen_singed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_singed'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
